<a href="https://colab.research.google.com/github/LuanPCunha/TCC/blob/main/RotinasDeLimpezaDaBaseDeDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rotinas de Limpeza

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Base de Dados Twitter

Análise da base de dados do Twitter com linguagem ofensiva

Pré - Processamento do texto

Classificação

Import e instalação das bibliotecas necessárias

In [ ]:
#Install e downloads
!pip install emoji
!pip install pandas
!pip install nltk
#nltk.download('all-nltk') #Demora um pouco

Collecting emoji
  Downloading emoji-1.7.0.tar.gz (175 kB)
     |████████████████████████████████| 175 kB 8.0 MB/s
Building wheels for collected packages: emoji
  Building wheel for emoji (setup.py) ... done
  Created wheel for emoji: filename=emoji-1.7.0-py3-none-any.whl size=171046 sha256=b7776c99a2769d69f84f6da9f18d3a701e02d856573091515f11ecf3b857c331
  Stored in directory: /root/.cache/pip/wheels/8a/4e/b6/57b01db010d17ef6ea9b40300af725ef3e210cb1acfb7ac8b6
Successfully built emoji
Installing collected packages: emoji
Successfully installed emoji-1.7.0
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (3.2.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from nltk) (1.15.0)

In [ ]:
#Imports
import pandas as pd
from nltk.tokenize import RegexpTokenizer
import re
import itertools

In [ ]:
# Definição de constantes

# Padrão RegEx
PADRAO_PALAVRAS_PT = r'[a-zA-Zà-úÀ-Ú]+'

# Quantidade tokens tweets pequeno
QUANT_TOKENS_MIN = 3

########## PATHS DE ARQUIVOS ##########
# Base completa bruta
PATH_BASE_COMPLETA_BRUTA = r"/content/drive/MyDrive/TCC/dados/tweets_coletados/base80k.csv"

# Base teste bruta
PATH_BASE_TESTE_BRUTA = r"/content/drive/MyDrive/TCC/dados/tweets_coletados/base_teste.csv"

# Dicionário de palavrões
PATH_DICT_PALAVROES = r"/content/drive/MyDrive/TCC/dados/dicionarios/badword_list.csv"

# Dicionário de internetes
PATH_DICT_INTERNETES = r"/content/drive/MyDrive/TCC/dados/dicionarios/internetes_list.csv"

# Dicionário de estados
PATH_DICT_ESTADOS = r"/content/drive/MyDrive/TCC/dados/dicionarios/estados_list.csv"

# Dicionário de expressões contraídas
PATH_DICT_EXPRESSOES = r"/content/drive/MyDrive/TCC/dados/dicionarios/dict_hate_contraidos.csv"

# Lista de vogais duplicadas
PATH_LIST_VOGAIS_DUPLICADAS = r"/content/drive/MyDrive/TCC/dados/dicionarios/vogais_duplicadas.csv"

# Lista de stopWords
PATH_LIST_STOP_WORDS_PT_BR = r"/content/drive/MyDrive/TCC/dados/dicionarios/stop_word_list.csv"

In [ ]:
#Carrega a base de dados
baseTweets = pd.read_csv(PATH_BASE_COMPLETA_BRUTA, index_col=0)
#baseTweets = baseTweets.sample(n=1000) #PEGANDO 1000 REGISTROS DA BASE PARA TESTE, REMOVER ISSO DEPOIS
baseTweets.head()

,id_str,created_at,text,entities.hashtags,place.full_name
0,1270007273088339969,Mon Jun 08 14:58:24 +0000 2020,@allantercalivre PARABÉNS @allantercalivre,[],"Sao Paulo, Brazil"
1,1270005650945343489,Mon Jun 08 14:51:57 +0000 2020,RT @franciscoedi11: @allantercalivre Eu queria...,[],NaN
2,1270002784742539264,Mon Jun 08 14:40:34 +0000 2020,@allantercalivre @EdnaBraga Gostei da pulseira...,[],"Sao Paulo, Brazil"
3,1270001502124417025,Mon Jun 08 14:35:28 +0000 2020,@allantercalivre @FBI Esses não irão ao encont...,[],"Recife, Brazil"
4,1270000103416266754,Mon Jun 08 14:29:54 +0000 2020,@allantercalivre Cadê eles ?\r\nTá faltando,[],"Nova Iguaçu, Brasil"

In [ ]:
baseTweets.shape

(82149, 5)

Fase 1
Definição das funções usadas na limpeza Etapas:

1. Remover menções (Remover @fulano)
2. Remover caracteres especiais, Remover caracteres de pontuação e Remover dígitos
3. Remover emojis
4. Expandir internetês
5. Normalizar nomes de estados (SP->São Paulo)
6. Retirar letras repetidas
7. Remover tweets com <3 tokens
8. Remover tweets repetidos (texto idêntico)

In [ ]:
# Main

# Carregando dicionários
tokenizer = RegexpTokenizer(PADRAO_PALAVRAS_PT)
dict_internetes = pd.read_csv(PATH_DICT_INTERNETES)
dict_estados = pd.read_csv(PATH_DICT_ESTADOS)
dict_expressoes = pd.read_csv(PATH_DICT_EXPRESSOES, encoding='latin-1')
list_vogais_duplicadas = pd.read_csv(PATH_LIST_VOGAIS_DUPLICADAS)

def pre_processamento(text):
    # Limpeza
    text = remover_mencao(text.lower()) # Remover menções
    text = re.sub(r'http\S+', '', text) # Remover links
    tokens = tokenizer.tokenize(text) # Remover caracteres especiais, pontuação, emojis e dígitos
    tokens = expandir_sigla(tokens,dict_internetes) # Expandir Internetes
    tokens = expandir_sigla(tokens,dict_estados) # Normalizar nomes de estado
    tokens = remover_letras_repetidas(tokens, list_vogais_duplicadas) # Retirar letras repetidas
    tokens = seta_tweet_pequeno_para_um(tokens) # Marca tweets pequenos

    text_limpo = " ".join(tokens)
    return text_limpo

# Remover menções   
def remover_mencao(tweet):
    tweet_sem_mencao = re.sub(r'[@]\w+', '', tweet)
    tweet_sem_mencao = " ".join(tweet_sem_mencao.split()) # Remover espaços a mais
    return tweet_sem_mencao

# ESSA FUNÇÃO É CASE-SENSITIVE
def expandir_sigla(tokens, dicionario):
    colunas_dicionario = dicionario.columns
    dicionario_py = dicionario.set_index(colunas_dicionario[0]).to_dict() # Converte Dataframe para dicionário python
    dicionario_py = dicionario_py[colunas_dicionario[1]]
    keys = list(dicionario_py.keys())

    indice = 0
    for token in tokens:
      if token in keys:
        tokens[indice] = dicionario_py[token]
      indice+=1
    
    return tokens

# Retirar letras repetidas
def remover_letras_repetidas(tokens, lista):
    lista = list(lista['vogais_duplicadas'])
    tokens_sem_letras_repetidas = []
    for token in tokens:
        flag = True
        if token not in lista: # Se for uma palavra com vogais dobradas não modifica o token
            for i in range(len(token)):
                # Se tiver "rr" ou "ss" não modifica o token
                try:
                    if (token[i].lower()=='r' and token[i+1].lower()=='r') or\
                        (token[i].lower()=='s' and token[i+1].lower()=='s'):
                        flag = False
                        break
                except:
                    break
            if flag:
                # Remove letras repetidas
                token = ''.join(c[0] for c in itertools.groupby(token))
        tokens_sem_letras_repetidas.append(token)
    return tokens_sem_letras_repetidas

# Marca tweets pequenos
def seta_tweet_pequeno_para_um(tokens):
    if len(tokens)<QUANT_TOKENS_MIN:
        tokens = '1'
    return tokens

In [ ]:
# Aplicar pré processamento na base
baseTweets['text_limpo'] = baseTweets['text'].apply(lambda x: pre_processamento(x))
baseTweets.head()

,id_str,created_at,text,entities.hashtags,place.full_name,text_limpo
0,1270007273088339969,Mon Jun 08 14:58:24 +0000 2020,@allantercalivre PARABÉNS @allantercalivre,[],"Sao Paulo, Brazil",1
1,1270005650945343489,Mon Jun 08 14:51:57 +0000 2020,RT @franciscoedi11: @allantercalivre Eu queria...,[],NaN,retwet eu queria compartilhar mas antes eu gos...
2,1270002784742539264,Mon Jun 08 14:40:34 +0000 2020,@allantercalivre @EdnaBraga Gostei da pulseira...,[],"Sao Paulo, Brazil",gostei da pulseira e da educação dele nossaaa ...
3,1270001502124417025,Mon Jun 08 14:35:28 +0000 2020,@allantercalivre @FBI Esses não irão ao encont...,[],"Recife, Brazil",esses não irão ao encontro e beijing
4,1270000103416266754,Mon Jun 08 14:29:54 +0000 2020,@allantercalivre Cadê eles ?\r\nTá faltando,[],"Nova Iguaçu, Brasil",cadê eles está faltando

In [ ]:
# Remover tweets marcados como pequenos e remove tweets repetidos(texto idêntico) 
baseTweets.drop_duplicates(subset='text_limpo', keep='first', inplace=True)

# apaga a linha com o texto = '1' que sobra
baseTweets = baseTweets[baseTweets['text_limpo']!='1']

In [ ]:
# Porque está diminuindo quando rodamos mais de uma vez ?
baseTweets.shape

(73462, 6)

In [ ]:
# Dropa colunas que não serão utilizadas
baseTweets.drop(['id_str', 'created_at','text','entities.hashtags','place.full_name','text'], axis='columns', inplace=True)

# Renomeia as colunas que sobraram
baseTweets.rename(columns = {'text_limpo': 'text'}, inplace = True)
baseTweets

                                                    text
1      retwet eu queria compartilhar mas antes eu gos...
2      gostei da pulseira e da educação dele nossaaa ...
3                   esses não irão ao encontro e beijing
4                                cadê eles está faltando
5      e eu me questionando quem é esse blogueiro sem...
...                                                  ...
82244  abençoado ano novo sua linda e querida obrigad...
82245        leva eles com a gente eles são amorzinhos d
82246    k sai daqui marivaldo tu me odeia né pelo jeito
82247  se tu nunca fumou maconha cole isso no seu mur...
82248                          k k ata eu sou meia sonsa

[73462 rows x 1 columns]

In [ ]:
baseTweets.to_csv('/content/drive/MyDrive/TCC/dados/processadas/Base1_Com_StopWords.csv') #Salva base limpa

Fase 2
remover stopswords

In [ ]:
# O arquivo "portuguese" contem Stopwords em Portugues
ptBr_stopwords = pd.read_csv(PATH_LIST_STOP_WORDS_PT_BR)
ptBr_stopwords.head(5)

  stopwords
0        de
1         a
2         o
3         e
4        do

In [ ]:
# Converte df de stopwords para lista
ptBr_stopwords = list(ptBr_stopwords['stopwords'])
ptBr_stopwords

In [ ]:
# Remove stopwords da coluna text
baseTweets['text'] = baseTweets['text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (ptBr_stopwords)]))
baseTweets

                                                    text
1      retwet queria compartilhar antes gostaria sabe...
2      gostei pulseira educação nossaaa muita elegânc...
3                                  irão encontro beijing
4                                          cadê faltando
5                   questionando é blogueiro blog juntos
...                                                  ...
82244  abençoado novo linda querida obrigada carinho ...
82245                            leva gente amorzinhos d
82246               k sai daqui marivaldo odeia né jeito
82247      fumou maconha cole mural curtir acha mentindo
82248                                 k k ata meia sonsa

[73462 rows x 1 columns]

In [ ]:
# Seta os tweets pequenos (<3) da coluna sem stop words para 1
baseTweets["text"] = baseTweets["text"].apply(lambda x: ' '.join(seta_tweet_pequeno_para_um(x.split())))

In [ ]:
# Remover tweets marcados como pequenos e remove tweets repetidos(texto idêntico) 
baseTweets.drop_duplicates(subset='text', keep='first', inplace=True)

# apaga a linha com o texto = '1' que sobra
baseTweets = baseTweets[baseTweets['text']!='1']

In [ ]:
baseTweets.shape

(64847, 1)

In [ ]:
baseTweets

                                                    text
1      retwet queria compartilhar antes gostaria sabe...
2      gostei pulseira educação nossaaa muita elegânc...
3                                  irão encontro beijing
5                   questionando é blogueiro blog juntos
6            renan caloteiro desonesto vejam link abaixo
...                                                  ...
82242  egoísmo é grande parte produto sociedade émile...
82244  abençoado novo linda querida obrigada carinho ...
82245                            leva gente amorzinhos d
82246               k sai daqui marivaldo odeia né jeito
82248                                 k k ata meia sonsa

[64847 rows x 1 columns]

In [ ]:
baseTweets.to_csv('/content/drive/MyDrive/TCC/dados/processadas/Base2_Sem_StopWords.csv') #Salva base limpa